# Generated by Django 3.1.7 on 2021-02-25 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basemodel')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=('posts.basemodel',),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d')),
                ('content', models.TextField()),
                ('content_img', models.ImageField(upload_to='posts/%Y/%m/%d')),
                ('comment', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('url', models.EmailField(max_length=254)),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_user_set', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(blank=True, to='posts.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('posts.basemodel',),
        ),
    ]
