# Generated by Django 3.1.7 on 2021-02-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210225_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
