# Generated by Django 3.1.7 on 2021-02-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210225_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d'),
        ),
    ]
