# Generated by Django 3.1.7 on 2021-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210225_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.URLField(),
        ),
    ]
