# Generated by Django 3.1.7 on 2021-02-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210225_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='url',
            new_name='post_url',
        ),
    ]
