# Generated by Django 3.1.7 on 2021-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210304_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/media/accounts/base_user.png', upload_to='accounts/%Y/%m'),
        ),
    ]
